services:

  sast-manger:
    build: sast-manager
    image: manager-img
    container_name: manager-con
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sast-db:5432/sast-data
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - sast-db
  # restart: "on-failure"

  sast-db:
    image: postgres:16.1
    container_name: db-con
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=sast-data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - sast-db-data:/var/lib/postgresql/data
  #    restart: "on-failure"

  sast-broker:
    build: sast-broker
    image: broker-img
    container_name: broker-con
    ports:
      - "7070:7070"
    depends_on:
      - sast-manger
  #    restart: "on-failure"

  sast-agent:
    build: sast-agent
    image: agent-img
    container_name: agent-con
    ports:
      - "6060:6060"
    depends_on:
      - sast-manger
  #    restart: "on-failure"

  sast-ui:
    build: sast-ui
    image: ui-img
    container_name: ui-con
    ports:
      - "3000:3000"
    depends_on:
      - sast-manager
#    restart: "on-failure"
