version: '3.8'

services:

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=L0ZEQh1yTbGhNNUE7-6wSQ
    volumes:
      - kafka-vol:/bitnami/kafka
    networks:
      - sast-network

  sast-db:
    image: postgres:16.1
    container_name: db-con
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=sast-data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - sast-db-data:/var/lib/postgresql/data
    networks:
      - sast-network

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sast-manager-1
      - sast-manager-2
    networks:
      - sast-network
  redis:
    image: redis:latest
    container_name: redis-balancer
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sast-network


  sast-manager-1:
    build: sast-manager
    image: manager-img
    container_name: manager-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sast-db:5432/sast-data
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MANAGER_ID: sast-manager-1
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - sast-db
    networks:
      - sast-network

  sast-manager-2:
    build: sast-manager
    image: manager-img
    container_name: manager-2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sast-db:5432/sast-data
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MANAGER_ID: sast-manager-2
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - sast-db
    networks:
      - sast-network

  sast-agent-1:
    build: sast-agent
    image: agent-img
    container_name: agent-1
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - kafka
    networks:
      - sast-network

  sast-agent-2:
    build: sast-agent
    image: agent-img
    container_name: agent-2
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - kafka
    networks:
      - sast-network

  sast-agent-3:
    build: sast-agent
    image: agent-img
    container_name: agent-3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - kafka
    networks:
      - sast-network

  sast-agent-4:
    build: sast-agent
    image: agent-img
    container_name: agent-4
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - kafka
    networks:
      - sast-network

  sast-agent-5:
    build: sast-agent
    image: agent-img
    container_name: agent-5
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - kafka
    networks:
      - sast-network

  sast-ui:
    build: sast-ui
    image: ui-img
    container_name: ui-con
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    networks:
      - sast-network

volumes:
  sast-db-data:
  kafka-vol:

networks:
  sast-network:
    driver: bridge
