events {}

http {
    upstream backend {
        server sast-manager-1:8080 max_fails=3 fail_timeout=5s;
        server sast-manager-2:8080 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://backend;
        }

        location /health {
            proxy_pass http://backend/health;
        }

    }
}
